"""Annotated Excel output renderer.

Creates a new .xlsx file with the left workbook as the base,
highlighting changed cells with colour coding and comments.
"""

from __future__ import annotations

from pathlib import Path

import openpyxl
from openpyxl.comments import Comment
from openpyxl.styles import Font, PatternFill
from openpyxl.utils import get_column_letter

from exceldiff import __version__
from exceldiff.comparison.models import ChangeType, WorkbookDiff, SheetDiff, CellDiff

# Colour fills for highlighting
_FILL_FORMULA = PatternFill("solid", fgColor="FFFFCC00")  # Yellow — formula changed
_FILL_STYLE = PatternFill("solid", fgColor="FFFFB347")    # Orange — style changed
_FILL_ADDED = PatternFill("solid", fgColor="FF90EE90")    # Light green — cell added
_FILL_REMOVED = PatternFill("solid", fgColor="FFFFCCCB")  # Light red — cell removed
_FILL_STRUCTURAL = PatternFill("solid", fgColor="FFADD8E6")  # Light blue — structural

_FONT_HEADER = Font(bold=True, size=12)
_FONT_SUBHEADER = Font(bold=True, size=10)
_FONT_LABEL = Font(bold=True, color="444444")


def render(
    diff: WorkbookDiff,
    output_path: str = "exceldiff_annotated.xlsx",
) -> str:
    """Render a WorkbookDiff as an annotated Excel file.

    Opens the left workbook as the base and highlights cells that differ.

    Args:
        diff: The comparison result to render.
        output_path: Path for the output .xlsx file.

    Returns:
        The absolute path to the generated file.
    """
    # Load left workbook as the base (with values, not formulas, for display)
    wb = openpyxl.load_workbook(diff.left_path, data_only=False)

    # Add summary sheet at the front
    _add_summary_sheet(wb, diff)

    # Annotate each sheet that has diffs
    for sheet_diff in diff.sheet_diffs:
        if sheet_diff.change_type == ChangeType.UNCHANGED:
            continue
        if sheet_diff.change_type == ChangeType.ADDED:
            _add_placeholder_sheet(wb, sheet_diff, "ADDED — only in right workbook")
            continue
        if sheet_diff.change_type == ChangeType.REMOVED:
            # Sheet exists in the left workbook; add a comment header
            if sheet_diff.sheet_name in wb.sheetnames:
                ws = wb[sheet_diff.sheet_name]
                ws.sheet_properties.tabColor = "FF0000"
            continue
        # MODIFIED — annotate cells
        if sheet_diff.sheet_name in wb.sheetnames:
            _annotate_sheet(wb[sheet_diff.sheet_name], sheet_diff)

    out = Path(output_path)
    wb.save(str(out))
    wb.close()
    return str(out.resolve())


def _add_summary_sheet(wb: openpyxl.Workbook, diff: WorkbookDiff) -> None:
    """Insert a summary sheet at the front of the workbook."""
    ws = wb.create_sheet("_ExcelDiff_Summary", 0)
    ws.column_dimensions["A"].width = 25
    ws.column_dimensions["B"].width = 40
    ws.column_dimensions["C"].width = 15
    ws.column_dimensions["D"].width = 15
    ws.column_dimensions["E"].width = 15

    row = 1
    ws.cell(row, 1, "ExcelDiff Report").font = _FONT_HEADER
    row += 1
    ws.cell(row, 1, f"Generated by ExcelDiff v{__version__}")
    row += 2

    ws.cell(row, 1, "Left file:").font = _FONT_LABEL
    ws.cell(row, 2, Path(diff.left_path).name)
    row += 1
    ws.cell(row, 1, "Right file:").font = _FONT_LABEL
    ws.cell(row, 2, Path(diff.right_path).name)
    row += 2

    # Stats
    ws.cell(row, 1, "Summary").font = _FONT_SUBHEADER
    row += 1
    stats = [
        ("Sheets compared", len(diff.sheets_in_both)),
        ("Sheets added", len(diff.sheets_only_in_right)),
        ("Sheets removed", len(diff.sheets_only_in_left)),
        ("Formula diffs", diff.total_formula_diffs),
        ("Style diffs", diff.total_style_diffs),
        ("Total cell diffs", diff.total_cell_diffs),
    ]
    for label, value in stats:
        ws.cell(row, 1, label).font = _FONT_LABEL
        ws.cell(row, 2, value)
        row += 1

    row += 1

    # Per-sheet breakdown
    ws.cell(row, 1, "Sheet Breakdown").font = _FONT_SUBHEADER
    row += 1
    headers = ["Sheet Name", "Status", "Formula Diffs", "Style Diffs", "Structural Diffs"]
    for col, h in enumerate(headers, 1):
        ws.cell(row, col, h).font = _FONT_LABEL
    row += 1

    for sd in diff.sheet_diffs:
        ws.cell(row, 1, sd.sheet_name)
        ws.cell(row, 2, sd.change_type.value.upper())
        if sd.change_type == ChangeType.MODIFIED:
            ws.cell(row, 3, sd.formula_diff_count)
            ws.cell(row, 4, sd.style_diff_count)
            ws.cell(row, 5, len(sd.structural_diffs))
        row += 1

    row += 1

    # Legend
    ws.cell(row, 1, "Colour Legend").font = _FONT_SUBHEADER
    row += 1
    legend = [
        (_FILL_FORMULA, "Formula changed"),
        (_FILL_STYLE, "Style changed"),
        (_FILL_ADDED, "Cell added (only in right)"),
        (_FILL_REMOVED, "Cell removed (only in left)"),
        (_FILL_STRUCTURAL, "Structural change"),
    ]
    for fill, description in legend:
        ws.cell(row, 1, "   ").fill = fill
        ws.cell(row, 2, description)
        row += 1

    ws.sheet_properties.tabColor = "1E40AF"


def _annotate_sheet(ws, sheet_diff: SheetDiff) -> None:
    """Annotate cells in a worksheet based on the diff results."""
    # Structural changes — add as comments on A1
    if sheet_diff.structural_diffs:
        struct_text = "STRUCTURAL CHANGES:\n"
        for prop in sheet_diff.structural_diffs:
            left = prop.left_value if prop.left_value is not None else "-"
            right = prop.right_value if prop.right_value is not None else "-"
            struct_text += f"  {prop.property_name}: {left} -> {right} [{prop.change_type.value}]\n"

        existing = ws["A1"].comment
        if existing:
            struct_text = existing.text + "\n\n" + struct_text
        ws["A1"].comment = Comment(struct_text, "ExcelDiff")
        ws["A1"].fill = _FILL_STRUCTURAL

    # Cell-level diffs
    for cd in sheet_diff.cell_diffs:
        _annotate_cell(ws, cd)

    # Set tab colour to indicate changes
    ws.sheet_properties.tabColor = "F59E0B"


def _annotate_cell(ws, cd: CellDiff) -> None:
    """Annotate a single cell with highlighting and a comment."""
    cell = ws[cd.coordinate]

    # Choose fill colour
    if cd.change_type == ChangeType.ADDED:
        cell.fill = _FILL_ADDED
    elif cd.change_type == ChangeType.REMOVED:
        cell.fill = _FILL_REMOVED
    elif cd.formula_changed:
        cell.fill = _FILL_FORMULA
    elif cd.style_changed:
        cell.fill = _FILL_STYLE

    # Build comment text
    lines = [f"ExcelDiff: {cd.change_type.value.upper()}"]
    for prop in cd.properties:
        left = prop.left_value if prop.left_value is not None else "-"
        right = prop.right_value if prop.right_value is not None else "-"
        lines.append(f"  {prop.property_name}: {left} -> {right}")

    cell.comment = Comment("\n".join(lines), "ExcelDiff")


def _add_placeholder_sheet(
    wb: openpyxl.Workbook,
    sheet_diff: SheetDiff,
    message: str,
) -> None:
    """Add a placeholder sheet for sheets that only exist in one workbook."""
    ws = wb.create_sheet(f"(+) {sheet_diff.sheet_name}")
    ws["A1"] = f"Sheet '{sheet_diff.sheet_name}' — {message}"
    ws["A1"].font = Font(bold=True, color="10B981")
    ws.column_dimensions["A"].width = 50
    ws.sheet_properties.tabColor = "10B981"
